### ISSUE TITLE
add rust-toolchain file to automatically use nightly

### ISSUE THREAD

**Issue by hardliner66** [Ved-s/cuprous#1]
You can add rust-toolchain file in order for cargo to automatically use the right rust version. See: https://rust-lang.github.io/rustup/overrides.html?#the-toolchain-file

**Comment by Ved-s** [comment]
Nightly is temporary, I'll make it use stable later

**Comment by Ved-s** [comment]
Also I'm not sure this will work with ci, it uses an action that installs specific version and targets

**Comment by hardliner66** [comment]
I checked and found nothing that would indicate installing a specific version. But you can install targets and components with a toolchain file. I've created a pull request and checked if it builds and it does.
